//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAeropuerto
{
    using System;
    using System.Collections.Generic;
    
    public partial class hangarr
    {
        public int id_hangar { get; set; }
        public string ubicacion { get; set; }
        public Nullable<int> capacidad { get; set; }
    }
}
