//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAeropuerto
{
    using System;
    using System.Collections.Generic;
    
    public partial class mantenimiento
    {
        public int id_mantenimiento { get; set; }
        public Nullable<int> id_avion { get; set; }
        public Nullable<int> id_mecanico { get; set; }
        public Nullable<System.DateTime> fecha_mantenimiento { get; set; }
    
        public virtual avion avion { get; set; }
        public virtual mecanicos mecanicos { get; set; }
    }
}
