//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAeropuerto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemaAeropuertoEntities : DbContext
    {
        public SistemaAeropuertoEntities()
            : base("name=SistemaAeropuertoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<avion> avion { get; set; }
        public virtual DbSet<azafata> azafata { get; set; }
        public virtual DbSet<Estadia> Estadia { get; set; }
        public virtual DbSet<hangarr> hangarr { get; set; }
        public virtual DbSet<mantenimiento> mantenimiento { get; set; }
        public virtual DbSet<mecanicos> mecanicos { get; set; }
        public virtual DbSet<piloto> piloto { get; set; }
        public virtual DbSet<propietario> propietario { get; set; }
        public virtual DbSet<vuelo> vuelo { get; set; }
    }
}
