//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAeropuerto
{
    using System;
    using System.Collections.Generic;
    
    public partial class vuelo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vuelo()
        {
            this.Estadia = new HashSet<Estadia>();
        }
    
        public int id_vuelo { get; set; }
        public Nullable<System.DateTime> fecha_vuelo { get; set; }
        public Nullable<int> id_avion { get; set; }
    
        public virtual avion avion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estadia> Estadia { get; set; }
    }
}
